CREATE TABLESPACE SRS
DATAFILE
  '/tmax1o/oradata/data01/TBL_PRDE_SRS.dbf' SIZE 33554432 REUSE AUTOEXTEND ON NEXT 33554432 MAXSIZE 2147483648

DEFAULT NOCOMPRESS
ONLINE
EXTENT MANAGEMENT LOCAL;




DROP USER PRDE_SRS CASCADE;
CREATE USER PRDE_SRS IDENTIFIED BY depl0y2@!8
DEFAULT TABLESPACE "SRS"
TEMPORARY TABLESPACE "TEMP"
ACCOUNT UNLOCK;


ALTER USER PRDE_SRS QUOTA UNLIMITED ON SRS;
GRANT CONNECT TO PRDE_SRS;
GRANT RESOURCE TO PRDE_SRS;



-- granting select on PRDE_TMAXIO1 schema
BEGIN
  FOR R IN (SELECT OWNER, TABLE_NAME FROM ALL_TABLES WHERE OWNER='PRDE_TMAXIO1') LOOP
    EXECUTE IMMEDIATE 'grant select on '||R.owner||'.'||R.table_name||' to PRDE_SRS';
  END LOOP;
END; 