export const REGISTER_START = "REGISTERING_START";
export const REGISTER_END = "REGISTERING_END";
export const VALIDATE_REGISTER_FORM = "VALIDATE_REG_FORM";
export const USER_LOCATION_START = "USR_LOCATION_START";
export const USER_LOCATION_END = "USR_LOCATION_END";

export const ACTIVATION_USER_START = "ACTIVATION_USR_START";
export const ACTIVATION_USER_END = "ACTIVATION_USR_END";

export const AUTHENTICATING = "AUTHENTICATING";
export const AUTHENTICATED = "AUTHENTICATING";


export const STUDENT_LOOKUP_FORM_CHANGE = "STUDENT_LOOKUP_FORM_CHANGE";
export const STUDENT_SEARCH_START = "STUDENT_SEARCH_START";
export const STUDENT_SEARCH_END = "STUDENT_SEARCH_END";
export const STUDENT_FOUND = "STUDENT_FOUND";
export const STUDENT_NOT_FOUND = "STUDENT_NOT_FOUND";


export let blockUIActions = [REGISTER_START, AUTHENTICATING, STUDENT_SEARCH_START];
export let unblockUIActions = [REGISTER_END, AUTHENTICATED, STUDENT_SEARCH_END];


